# Generated by Django 5.2.5 on 2025-09-02 13:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='이메일')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='사용자명')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='이름')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='성')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='전화번호')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='프로필 이미지')),
                ('profile_image_url', models.URLField(blank=True, max_length=500, verbose_name='프로필 이미지 URL')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('login_method', models.CharField(choices=[('email', '이메일'), ('google', '구글'), ('kakao', '카카오')], default='email', max_length=20, verbose_name='가입 방법')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 여부')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_marketing_agreed', models.BooleanField(default=False, verbose_name='마케팅 수신 동의')),
                ('is_terms_agreed', models.BooleanField(default=True, verbose_name='이용약관 동의')),
                ('is_privacy_agreed', models.BooleanField(default=True, verbose_name='개인정보처리방침 동의')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao')], max_length=20, verbose_name='제공자')),
                ('social_id', models.CharField(max_length=255, verbose_name='소셜 ID')),
                ('access_token', models.TextField(blank=True, verbose_name='액세스 토큰')),
                ('refresh_token', models.TextField(blank=True, verbose_name='리프레시 토큰')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='토큰 만료일')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='추가 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='연동일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '소셜 계정',
                'verbose_name_plural': '소셜 계정들',
                'db_table': 'social_accounts',
                'unique_together': {('provider', 'social_id')},
            },
        ),
    ]
