# Generated by Django 5.2.5 on 2025-09-09 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='캘린더 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('calendar_type', models.CharField(choices=[('personal', '개인 캘린더'), ('shared', '공유 캘린더')], default='personal', max_length=10, verbose_name='캘린더 유형')),
                ('image', models.ImageField(blank=True, null=True, upload_to='calendar_images/', verbose_name='캘린더 이미지')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='캘린더 색상')),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='공유 토큰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_calendars', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '캘린더',
                'verbose_name_plural': '캘린더',
                'db_table': 'calendars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='메모')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('start_date', models.DateTimeField(verbose_name='시작 시간')),
                ('end_date', models.DateTimeField(verbose_name='종료 시간')),
                ('all_day', models.BooleanField(default=False, verbose_name='종일 일정')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='색상')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendar', verbose_name='캘린더')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정',
                'db_table': 'events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(max_length=254, verbose_name='초대받은 이메일')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('member', '참여자')], default='member', max_length=10, verbose_name='역할')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락'), ('declined', '거절')], default='pending', max_length=10, verbose_name='상태')),
                ('invitation_token', models.CharField(max_length=64, unique=True, verbose_name='초대 토큰')),
                ('message', models.TextField(blank=True, verbose_name='초대 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='초대일')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='응답일')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='calendars.calendar', verbose_name='캘린더')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대받은 사람')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대한 사람')),
            ],
            options={
                'verbose_name': '캘린더 초대',
                'verbose_name_plural': '캘린더 초대',
                'db_table': 'calendar_invitations',
                'unique_together': {('calendar', 'invitee_email')},
            },
        ),
        migrations.CreateModel(
            name='CalendarMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('member', '참여자')], default='member', max_length=10, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='참여일')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='calendars.calendar', verbose_name='캘린더')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '캘린더 멤버',
                'verbose_name_plural': '캘린더 멤버',
                'db_table': 'calendar_members',
                'unique_together': {('calendar', 'user')},
            },
        ),
    ]
