# Generated by Django 5.2.5 on 2025-09-12 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.CreateModel(
            name='CalendarTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=7, verbose_name='태그 색상')),
                ('name', models.CharField(max_length=50, verbose_name='태그 이름')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='calendars.calendar', verbose_name='캘린더')),
            ],
            options={
                'verbose_name': '캘린더 태그',
                'verbose_name_plural': '캘린더 태그',
                'db_table': 'calendar_tags',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendars.calendartag', verbose_name='태그'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['calendar', 'start_date'], name='events_calenda_e342b2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['calendar', 'tag'], name='events_calenda_da9a59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendartag',
            unique_together={('calendar', 'color')},
        ),
    ]
